apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: climbconnectapi-database
  namespace: student-r-lehner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
